### PR TITLE
release 2.6

### PR DESCRIPTION
**Pull request by arademaker**
Hi @dan-zeman , this is our proposal for release 2.6. Unfortunately, we didn't have time to fix all validation errors. They will be fixed in the next release.

### CODE REVIEW

**Comment by dan-zeman** [comment]
Hi @arademaker, @ceramisch and all, thanks for the efforts! As always, the release process merges dev into master without using pull requests, so I am going to close this PR now.

However, the current contents of the dev branch unfortunately contains newly introduced error types that were not present in UD 2.5. These are the errors labeled `files`, `invalid-line`, `overlapping-word-intervals`, `word-id-sequence`, `skipped-corrupt-tree`, `text-extra-chars`, `text-form-mismatch`, `multiple-roots`, `non-tree`. We cannot release the data with these errors; that's why the [validation page](https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl) no longer lists the treebank as LEGACY (purple) and instead lists it as ERROR (red).

I can wait a few extra days if you are able to fix the data (I can probably wait as long as until May 8). Otherwise, I would move the current dev into a new branch, then replace the conllu files with those from UD 2.5 and proceed with the release, and after UD 2.6 is released you would merge the bypass branch back into dev and continue with the development.

**Comment by arademaker** [comment]
I will try to fix the problems

**Comment by dan-zeman** [comment]
Thanks, Alexandre!

**Comment by arademaker** [comment]
Hi @dan-zeman , running the validate.py script myself, in the current dev branch:

```
cat *.conllu | python3 ~/work/ud-tools/validate.py --lang pt --max-err 0 2> gsd.log
```

I didn't find the `invalid-line` error reported by you [here](https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl?UD_Portuguese-GSD). Moreover, I opened the test file and sentence s830 does not present any strange line. 

Regarding the `files` error, this is caused by the `script` directory. The English-EWT contains a directory called `do-not-release`. What is the restrictions for the `dev` branch? I can move this directory for a `workbench` branch was we do in http://github.com/universaldependencies/UD_Portuguese-Bosque, for sure. I just want to understand the restrictions on the `dev` branch.

I also didn't find in my local error log the error `overlapping-word-intervals`. What this error means? After inspecting some sentences like `train-s2876` I didn't find anything strange at all.

Can you double-check your report? So I can continue investigating the errors?

**Comment by dan-zeman** [comment]
Regarding the `files` error: the `dev` branch should contain the (up to) three CoNLL-U files, plus README.md, LICENSE.txt, CONTRIBUTING.md, stats.xml and .gitignore. Optionally, there can be a subfolder named `not-to-release`. Everything else that the maintainers want to keep in the dev branch should be under this subfolder.

**Comment by dan-zeman** [comment]
As for the basic format error in sentence 830, it is a result of a git merge conflict (and thus exists only on the validation server). This is quite strange because I do not edit the contents of the repos on that server, hence conflicts are not expected. Looking at the log on the validation server, I see two commits by @ceramisch from May 1 19:07 (71072b1ecdbdfd15841cf18edd387ffb0bd94aef) and 20:25 (c036820326ed77d9fb2dafc35c73b21195c3ba31). However, when I pull the dev branch to my laptop, these commits are not there. Instead, there are four commits by @arademaker later that day (45e770a1942e83ed80b4b82ea2a821bee8c3f667, 62efbad6d06cfa68ba545a5f7d6ffa29c008e8d6, d8d8e4c6f4642f74c6a99e1ad8f7b8e5153eb9c3, 2938fd38e8a2473c3bb89cd9ae932a1eb1813bbc). Indeed, both commit sequences have a common parent (523366b from February 5), but the one by @ceramisch is now probably a dead unnamed branch. This seems to be responsible for the conflict on the validation server because it has commits that the Github remote doesn't have. Is it possible that the commit history was altered?

**Comment by arademaker** [comment]
yes, I have edited the commit history to avoid the unwanted duplication of the repository size. I have documented it in issue #5

**Comment by arademaker** [comment]
For the `file`, I created a `workbench` branch and moved the `scripts` directory to there.

**Comment by dan-zeman** [comment]
Okay. I've managed to fix it. The treebank is back at the LEGACY status.

**Pull request closed without merging**
